### PR TITLE
Copy to clip board feature while search

### PR DESCRIPTION
**Pull request by saukumar95**
Added copy to clipboard feature when user search for password in system for website then it automatically saves on clipboard to easy to use.

### CODE REVIEW

**Review by guru3654 — COMMENTED** [review]
Encryption of password while copying to the clipboard is required

**Comment by saukumar95** [comment]
> Encryption of password while copying to the clipboard is required

If we encrypt password string and then copy then while using to any client like text editor or website text file. It put encrypted password not original string. According to me encryption of password and other things around it can be thing separately. Like how can we save passwords in json/csv file in encrypted mode and while searching or copying to clip board we will copy original string.

**Comment by guru3654** [comment]
> > Encryption of password while copying to the clipboard is required
> 
> If we encrypt password string and then copy then while using to any client like text editor or website text file. It put encrypted password not original string. According to me encryption of password and other things around it can be thing separately. Like how can we save passwords in json/csv file in encrypted mode and while searching or copying to clip board we will copy original string.

Can't we use any basic encryption technique and encode it while copying to clipboard and the decode while pasting?

**Review by guru3654 — APPROVED** [review]

**Comment by saukumar95** [comment]
> > > Encryption of password while copying to the clipboard is required
> > 
> > 
> > If we encrypt password string and then copy then while using to any client like text editor or website text file. It put encrypted password not original string. According to me encryption of password and other things around it can be thing separately. Like how can we save passwords in json/csv file in encrypted mode and while searching or copying to clip board we will copy original string.
> 
> Can't we use any basic encryption technique and encode it while copying to clipboard and the decode while pasting?

We can use for sure. Not only basic encryption but advance as well. Problem here is decryption should happen at client application like if user paste in website there we need decryption, which is not in our control.

**Pull request merged**
